name: Infra AI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tensorflow pandas scikit-learn matplotlib networkx stable-baselines3[extra] gym

    - name: Run LSTM anomaly detection
      run: |
        python Infra/infraservices/ml/lstm.py

    - name: Generate GNN graph visualization
      run: |
        python Infra/infraservices/ml/gnn.py

    - name: Train PPO model
      run: |
        python Infra/infraservices/ml/ppo.py

